#!/usr/bin/env python3
"""Generate a Gmsh .geo file for 2D flow around a circular cylinder.

Creates a structured/unstructured hybrid mesh suitable for laminar vortex
shedding simulations at Re ≈ 200. Uses the OpenCASCADE geometry kernel for
boolean operations and boundary-layer insertion.

Usage:
    python3 generate_cylinder_geo.py --output constant/cylinder.geo
"""

import argparse
from pathlib import Path


def parse_args():
    p = argparse.ArgumentParser(
        description="Generate Gmsh .geo file for cylinder-in-crossflow."
    )
    p.add_argument(
        "--output",
        type=str,
        default="constant/cylinder.geo",
        help="Output .geo file path (default: constant/cylinder.geo)",
    )
    # Domain
    p.add_argument("--xmin", type=float, default=-8.0)
    p.add_argument("--xmax", type=float, default=25.0)
    p.add_argument("--ymin", type=float, default=-8.0)
    p.add_argument("--ymax", type=float, default=8.0)
    p.add_argument("--span", type=float, default=0.1,
                   help="Spanwise thickness (pseudo-2D)")
    # Cylinder
    p.add_argument("--cx", type=float, default=0.0)
    p.add_argument("--cy", type=float, default=0.0)
    p.add_argument("--radius", type=float, default=0.5)
    # Mesh sizing
    p.add_argument("--mesh-size-cylinder", type=float, default=0.05,
                   help="Near-body element size")
    p.add_argument("--mesh-size-farfield", type=float, default=0.5)
    p.add_argument("--first-layer", type=float, default=0.01,
                   help="First BL cell height")
    p.add_argument("--bl-ratio", type=float, default=1.15,
                   help="Boundary layer growth ratio")
    p.add_argument("--bl-thickness", type=float, default=0.15,
                   help="Total boundary layer thickness")
    p.add_argument("--near-size", type=float, default=0.05,
                   help="Near-body refinement element size")
    p.add_argument("--near-dist", type=float, default=2.0,
                   help="Near-body refinement distance from cylinder")
    # Wake refinement
    p.add_argument("--wake-xmin", type=float, default=0.0)
    p.add_argument("--wake-xmax", type=float, default=20.0)
    p.add_argument("--wake-ymin", type=float, default=-3.0)
    p.add_argument("--wake-ymax", type=float, default=3.0)
    p.add_argument("--wake-size", type=float, default=0.08)
    return p.parse_args()


def write_geo(args):
    """Write a complete Gmsh .geo file."""
    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)

    geo = []
    g = geo.append

    g("// Gmsh .geo — 2D cylinder in crossflow")
    g("// Auto-generated by generate_cylinder_geo.py")
    g("SetFactory(\"OpenCASCADE\");")
    g("")

    # ── Geometry ──────────────────────────────────────────────────────────
    g("// Domain rectangle")
    g(f"Rectangle(1) = {{{args.xmin}, {args.ymin}, 0, "
      f"{args.xmax - args.xmin}, {args.ymax - args.ymin}}};")
    g("")

    g("// Cylinder disk (will be subtracted)")
    g(f"Disk(2) = {{{args.cx}, {args.cy}, 0, {args.radius}}};")
    g("")

    g("// Boolean difference: domain minus cylinder")
    g("BooleanDifference{ Surface{1}; Delete; }{ Surface{2}; Delete; };")
    g("")

    # After BooleanDifference with OpenCASCADE, the resulting surface is 1
    # and the curves are renumbered. We need to identify them.
    # Use Gmsh's automatic tagging — the outer rectangle edges come first,
    # then the cylinder circle.

    # ── Mesh sizing ───────────────────────────────────────────────────────
    g("// --- Mesh size fields ---")
    g("")

    # Field 1: Distance from cylinder curves
    g("Field[1] = Distance;")
    g("Field[1].CurvesList = {5};")  # curve 5 is the cylinder after boolean
    g("Field[1].Sampling = 200;")
    g("")

    # Field 2: Near-body refinement (threshold on distance)
    g("Field[2] = Threshold;")
    g("Field[2].InField = 1;")
    g(f"Field[2].SizeMin = {args.near_size};")
    g(f"Field[2].SizeMax = {args.mesh_size_farfield};")
    g(f"Field[2].DistMin = {0.1};")
    g(f"Field[2].DistMax = {args.near_dist};")
    g("")

    # Field 3: Wake refinement box
    g("Field[3] = Box;")
    g(f"Field[3].VIn  = {args.wake_size};")
    g(f"Field[3].VOut = {args.mesh_size_farfield};")
    g(f"Field[3].XMin = {args.wake_xmin};")
    g(f"Field[3].XMax = {args.wake_xmax};")
    g(f"Field[3].YMin = {args.wake_ymin};")
    g(f"Field[3].YMax = {args.wake_ymax};")
    g(f"Field[3].ZMin = {-1.0};")
    g(f"Field[3].ZMax = {1.0};")
    g(f"Field[3].Thickness = {0.5};")
    g("")

    # Field 4: Min of all fields
    g("Field[4] = Min;")
    g("Field[4].FieldsList = {2, 3};")
    g("Field[4].BackgroundField = 4;")
    g("")

    # Background field
    g("Background Field = 4;")
    g("")

    # Global mesh options
    g(f"Mesh.CharacteristicLengthMax = {args.mesh_size_farfield};")
    g(f"Mesh.CharacteristicLengthMin = {args.first_layer};")
    g("")

    # ── Boundary layer ────────────────────────────────────────────────────
    g("// Boundary layer around cylinder")
    g("Field[10] = BoundaryLayer;")
    g("Field[10].CurvesList = {5};")
    g(f"Field[10].Size = {args.first_layer};")
    g(f"Field[10].Ratio = {args.bl_ratio};")
    g(f"Field[10].Thickness = {args.bl_thickness};")
    g("Field[10].Quads = 1;")
    g("Field[10].IntersectMetrics = 0;")
    g("BoundaryLayer Field = 10;")
    g("")

    # ── Extrusion (pseudo-2D) ─────────────────────────────────────────────
    g("// Extrude surface mesh one layer in z for pseudo-2D")
    g(f"Extrude {{0, 0, {args.span}}} {{")
    g("    Surface{1};")
    g("    Layers{1};")
    g("    Recombine;")
    g("}")
    g("")

    # ── Recombine surface mesh to quads where possible ────────────────────
    g("Mesh.RecombineAll = 1;")
    g("Mesh.Algorithm = 8;  // Frontal-Delaunay for quads")
    g("")

    # ── Physical groups ───────────────────────────────────────────────────
    # After extrusion of the Boolean-differenced surface in OpenCASCADE:
    # The original 2D surface (1) becomes the front face.
    # Gmsh creates new surfaces for the extruded sides and back face.
    #
    # Typical tag assignment after BooleanDifference + Extrude:
    #   Curves of the bottom rectangle face:
    #     1 = bottom, 2 = right, 3 = top, 4 = left, 5 = cylinder
    #   After extrusion:
    #     Surface 1 = original front face (z=0)
    #     Surface 2 = extruded back face (z=span)
    #     Surfaces 3..7 = side walls from extrusion of curves 1..5
    #       3 = bottom wall (from curve 1)
    #       4 = right / outlet (from curve 2)
    #       5 = top wall (from curve 3)
    #       6 = left / inlet (from curve 4)
    #       7 = cylinder wall (from curve 5)
    #     Volume 1 = the extruded volume
    #
    # NOTE: Gmsh OpenCASCADE tag numbering can vary with version.
    # The Allrun pipeline uses changeDictionary to fix patch types,
    # so small tag shifts are tolerable — the names are what matter.

    g("// Physical groups for OpenFOAM boundary patches")
    g('Physical Surface("inlet")        = {6};')
    g('Physical Surface("outlet")       = {4};')
    g('Physical Surface("top")          = {5};')
    g('Physical Surface("bottom")       = {3};')
    g('Physical Surface("cylinder")     = {7};')
    g('Physical Surface("frontAndBack") = {1, 2};')
    g("")
    g('Physical Volume("fluid") = {1};')
    g("")

    g("// ── End of .geo file ──")

    out.write_text("\n".join(geo) + "\n")
    print(f"Wrote {out}  ({len(geo)} lines)")


def main():
    args = parse_args()
    write_geo(args)


if __name__ == "__main__":
    main()
